FROM python:3.14-alpine
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /src

# Install dependencies
COPY ./uv.lock ./pyproject.toml ./
RUN uv sync --compile-bytecode --no-cache --no-dev
ENV PATH="/src/.venv/bin:$PATH"

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1

ARG WORKSPACE
ENV WORKSPACE=${WORKSPACE}

EXPOSE ${BACKEND__RUN__PORT}

CMD uvicorn llmmo.main:app --reload --host 0.0.0.0 --port ${BACKEND__RUN__PORT}